version: '3.8'

services:
  tennis-app:
    build: .
    container_name: tennis_prediction
    restart: unless-stopped
    ports:
      - "0.0.0.0:5001:5001"
    volumes:
      - ./tennis_data_enhanced:/app/tennis_data_enhanced
      - ./tennis_models:/app/tennis_models
      - ./betting_data:/app/betting_data
      - ./logs:/app/logs
    environment:
      - FLASK_ENV=production
    env_file:
      - .env.production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Redis для кеширования (опционально)
  redis:
    image: redis:7-alpine
    container_name: tennis_redis
    restart: unless-stopped
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  redis_data:
